language: python
python:
  - "3.6.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
services:
  - postgresql
addons:
  postgresql: "9.5"

before_script:
  - psql -c "CREATE USER etomovich WITH PASSWORD 'etomovich';" -U postgres
  - psql -c 'CREATE DATABASE sendit_db' -U etomovich
  - psql -c 'CREATE DATABASE sendit_test_db' -U etomovich
  - psql -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public to etomovich;" -U postgres

before_script:
  - export PYTHONPATH=`pwd`
# command to run tests
script: 
  - nosetests courier_app/tests --with-coverage --cover-package=courier_app
after_success:
  - coverallslanguage: python
  - coveralls