language: python
python:
  - "3.2"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - export PYTHONPATH=`pwd`
# command to run tests
script: 
  - nosetests courier_app/tests --with-coverage --cover-package=courier_app
after_success:
  - coverallslanguage: python
  - coveralls